services:
  - type: web
    name: store-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"  #em produçao deve ficar true
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: false  # deploy via deploy hook apos github actions ok
